on: [push, pull_request]

jobs:
  test_notify:
    runs-on: ubuntu-latest
    name: Test the action on success
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Success
        run: exit 0
      - run: npm install
      - name: Action
        uses: ./ 
        if: always()
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_TOKEN }}
          channel: some-slack-channel
  test_ko:
    runs-on: ubuntu-latest
    name: Test the action on failure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Failure
        run: exit 1
      - run: npm install
      - name: Action
        uses: ./
        if: always()
        with:
            job-status: ${{ job.status }}
            slack-bot-token: ${{ secrets.SLACK_TOKEN }}
            channel: random